// Code generated by "sortnet"; DO NOT EDIT.
package networks

import "sort"

func Batcher16(a sort.Interface) {
	if !a.Less(0, 1) {
		a.Swap(0, 1)
	}
	if !a.Less(2, 3) {
		a.Swap(2, 3)
	}
	if !a.Less(0, 2) {
		a.Swap(0, 2)
	}
	if !a.Less(1, 3) {
		a.Swap(1, 3)
	}
	if !a.Less(1, 2) {
		a.Swap(1, 2)
	}
	if !a.Less(4, 5) {
		a.Swap(4, 5)
	}
	if !a.Less(6, 7) {
		a.Swap(6, 7)
	}
	if !a.Less(4, 6) {
		a.Swap(4, 6)
	}
	if !a.Less(5, 7) {
		a.Swap(5, 7)
	}
	if !a.Less(5, 6) {
		a.Swap(5, 6)
	}
	if !a.Less(0, 4) {
		a.Swap(0, 4)
	}
	if !a.Less(2, 6) {
		a.Swap(2, 6)
	}
	if !a.Less(2, 4) {
		a.Swap(2, 4)
	}
	if !a.Less(1, 5) {
		a.Swap(1, 5)
	}
	if !a.Less(3, 7) {
		a.Swap(3, 7)
	}
	if !a.Less(3, 5) {
		a.Swap(3, 5)
	}
	if !a.Less(1, 2) {
		a.Swap(1, 2)
	}
	if !a.Less(3, 4) {
		a.Swap(3, 4)
	}
	if !a.Less(5, 6) {
		a.Swap(5, 6)
	}
	if !a.Less(8, 9) {
		a.Swap(8, 9)
	}
	if !a.Less(10, 11) {
		a.Swap(10, 11)
	}
	if !a.Less(8, 10) {
		a.Swap(8, 10)
	}
	if !a.Less(9, 11) {
		a.Swap(9, 11)
	}
	if !a.Less(9, 10) {
		a.Swap(9, 10)
	}
	if !a.Less(12, 13) {
		a.Swap(12, 13)
	}
	if !a.Less(14, 15) {
		a.Swap(14, 15)
	}
	if !a.Less(12, 14) {
		a.Swap(12, 14)
	}
	if !a.Less(13, 15) {
		a.Swap(13, 15)
	}
	if !a.Less(13, 14) {
		a.Swap(13, 14)
	}
	if !a.Less(8, 12) {
		a.Swap(8, 12)
	}
	if !a.Less(10, 14) {
		a.Swap(10, 14)
	}
	if !a.Less(10, 12) {
		a.Swap(10, 12)
	}
	if !a.Less(9, 13) {
		a.Swap(9, 13)
	}
	if !a.Less(11, 15) {
		a.Swap(11, 15)
	}
	if !a.Less(11, 13) {
		a.Swap(11, 13)
	}
	if !a.Less(9, 10) {
		a.Swap(9, 10)
	}
	if !a.Less(11, 12) {
		a.Swap(11, 12)
	}
	if !a.Less(13, 14) {
		a.Swap(13, 14)
	}
	if !a.Less(0, 8) {
		a.Swap(0, 8)
	}
	if !a.Less(4, 12) {
		a.Swap(4, 12)
	}
	if !a.Less(4, 8) {
		a.Swap(4, 8)
	}
	if !a.Less(2, 10) {
		a.Swap(2, 10)
	}
	if !a.Less(6, 14) {
		a.Swap(6, 14)
	}
	if !a.Less(6, 10) {
		a.Swap(6, 10)
	}
	if !a.Less(2, 4) {
		a.Swap(2, 4)
	}
	if !a.Less(6, 8) {
		a.Swap(6, 8)
	}
	if !a.Less(10, 12) {
		a.Swap(10, 12)
	}
	if !a.Less(1, 9) {
		a.Swap(1, 9)
	}
	if !a.Less(5, 13) {
		a.Swap(5, 13)
	}
	if !a.Less(5, 9) {
		a.Swap(5, 9)
	}
	if !a.Less(3, 11) {
		a.Swap(3, 11)
	}
	if !a.Less(7, 15) {
		a.Swap(7, 15)
	}
	if !a.Less(7, 11) {
		a.Swap(7, 11)
	}
	if !a.Less(3, 5) {
		a.Swap(3, 5)
	}
	if !a.Less(7, 9) {
		a.Swap(7, 9)
	}
	if !a.Less(11, 13) {
		a.Swap(11, 13)
	}
	if !a.Less(1, 2) {
		a.Swap(1, 2)
	}
	if !a.Less(3, 4) {
		a.Swap(3, 4)
	}
	if !a.Less(5, 6) {
		a.Swap(5, 6)
	}
	if !a.Less(7, 8) {
		a.Swap(7, 8)
	}
	if !a.Less(9, 10) {
		a.Swap(9, 10)
	}
	if !a.Less(11, 12) {
		a.Swap(11, 12)
	}
	if !a.Less(13, 14) {
		a.Swap(13, 14)
	}
}
