// Code generated by "sortnet"; DO NOT EDIT.
package networks

import "sort"

// Bitonic8 sorts 8-element slice in an oblivious fashion.
func Bitonic8(a sort.Interface) {
	if !a.Less(0, 1) {
		a.Swap(0, 1)
	}
	if !a.Less(2, 3) {
		a.Swap(2, 3)
	}
	if !a.Less(4, 5) {
		a.Swap(4, 5)
	}
	if !a.Less(6, 7) {
		a.Swap(6, 7)
	}
	if !a.Less(0, 3) {
		a.Swap(0, 3)
	}
	if !a.Less(1, 2) {
		a.Swap(1, 2)
	}
	if !a.Less(0, 1) {
		a.Swap(0, 1)
	}
	if !a.Less(2, 3) {
		a.Swap(2, 3)
	}
	if !a.Less(4, 7) {
		a.Swap(4, 7)
	}
	if !a.Less(5, 6) {
		a.Swap(5, 6)
	}
	if !a.Less(4, 5) {
		a.Swap(4, 5)
	}
	if !a.Less(6, 7) {
		a.Swap(6, 7)
	}
	if !a.Less(0, 7) {
		a.Swap(0, 7)
	}
	if !a.Less(1, 6) {
		a.Swap(1, 6)
	}
	if !a.Less(2, 5) {
		a.Swap(2, 5)
	}
	if !a.Less(3, 4) {
		a.Swap(3, 4)
	}
	if !a.Less(0, 2) {
		a.Swap(0, 2)
	}
	if !a.Less(1, 3) {
		a.Swap(1, 3)
	}
	if !a.Less(4, 6) {
		a.Swap(4, 6)
	}
	if !a.Less(5, 7) {
		a.Swap(5, 7)
	}
	if !a.Less(0, 1) {
		a.Swap(0, 1)
	}
	if !a.Less(2, 3) {
		a.Swap(2, 3)
	}
	if !a.Less(4, 5) {
		a.Swap(4, 5)
	}
	if !a.Less(6, 7) {
		a.Swap(6, 7)
	}
}
