// Code generated by "sortnet"; DO NOT EDIT.
package networks

import "sort"

func Bitonic16(a sort.Interface) {
	if !a.Less(0, 1) {
		a.Swap(0, 1)
	}
	if !a.Less(2, 3) {
		a.Swap(2, 3)
	}
	if !a.Less(4, 5) {
		a.Swap(4, 5)
	}
	if !a.Less(6, 7) {
		a.Swap(6, 7)
	}
	if !a.Less(8, 9) {
		a.Swap(8, 9)
	}
	if !a.Less(10, 11) {
		a.Swap(10, 11)
	}
	if !a.Less(12, 13) {
		a.Swap(12, 13)
	}
	if !a.Less(14, 15) {
		a.Swap(14, 15)
	}
	if !a.Less(0, 3) {
		a.Swap(0, 3)
	}
	if !a.Less(1, 2) {
		a.Swap(1, 2)
	}
	if !a.Less(0, 1) {
		a.Swap(0, 1)
	}
	if !a.Less(2, 3) {
		a.Swap(2, 3)
	}
	if !a.Less(4, 7) {
		a.Swap(4, 7)
	}
	if !a.Less(5, 6) {
		a.Swap(5, 6)
	}
	if !a.Less(4, 5) {
		a.Swap(4, 5)
	}
	if !a.Less(6, 7) {
		a.Swap(6, 7)
	}
	if !a.Less(8, 11) {
		a.Swap(8, 11)
	}
	if !a.Less(9, 10) {
		a.Swap(9, 10)
	}
	if !a.Less(8, 9) {
		a.Swap(8, 9)
	}
	if !a.Less(10, 11) {
		a.Swap(10, 11)
	}
	if !a.Less(12, 15) {
		a.Swap(12, 15)
	}
	if !a.Less(13, 14) {
		a.Swap(13, 14)
	}
	if !a.Less(12, 13) {
		a.Swap(12, 13)
	}
	if !a.Less(14, 15) {
		a.Swap(14, 15)
	}
	if !a.Less(0, 7) {
		a.Swap(0, 7)
	}
	if !a.Less(1, 6) {
		a.Swap(1, 6)
	}
	if !a.Less(2, 5) {
		a.Swap(2, 5)
	}
	if !a.Less(3, 4) {
		a.Swap(3, 4)
	}
	if !a.Less(0, 2) {
		a.Swap(0, 2)
	}
	if !a.Less(1, 3) {
		a.Swap(1, 3)
	}
	if !a.Less(4, 6) {
		a.Swap(4, 6)
	}
	if !a.Less(5, 7) {
		a.Swap(5, 7)
	}
	if !a.Less(0, 1) {
		a.Swap(0, 1)
	}
	if !a.Less(2, 3) {
		a.Swap(2, 3)
	}
	if !a.Less(4, 5) {
		a.Swap(4, 5)
	}
	if !a.Less(6, 7) {
		a.Swap(6, 7)
	}
	if !a.Less(8, 15) {
		a.Swap(8, 15)
	}
	if !a.Less(9, 14) {
		a.Swap(9, 14)
	}
	if !a.Less(10, 13) {
		a.Swap(10, 13)
	}
	if !a.Less(11, 12) {
		a.Swap(11, 12)
	}
	if !a.Less(8, 10) {
		a.Swap(8, 10)
	}
	if !a.Less(9, 11) {
		a.Swap(9, 11)
	}
	if !a.Less(12, 14) {
		a.Swap(12, 14)
	}
	if !a.Less(13, 15) {
		a.Swap(13, 15)
	}
	if !a.Less(8, 9) {
		a.Swap(8, 9)
	}
	if !a.Less(10, 11) {
		a.Swap(10, 11)
	}
	if !a.Less(12, 13) {
		a.Swap(12, 13)
	}
	if !a.Less(14, 15) {
		a.Swap(14, 15)
	}
	if !a.Less(0, 15) {
		a.Swap(0, 15)
	}
	if !a.Less(1, 14) {
		a.Swap(1, 14)
	}
	if !a.Less(2, 13) {
		a.Swap(2, 13)
	}
	if !a.Less(3, 12) {
		a.Swap(3, 12)
	}
	if !a.Less(4, 11) {
		a.Swap(4, 11)
	}
	if !a.Less(5, 10) {
		a.Swap(5, 10)
	}
	if !a.Less(6, 9) {
		a.Swap(6, 9)
	}
	if !a.Less(7, 8) {
		a.Swap(7, 8)
	}
	if !a.Less(0, 4) {
		a.Swap(0, 4)
	}
	if !a.Less(1, 5) {
		a.Swap(1, 5)
	}
	if !a.Less(2, 6) {
		a.Swap(2, 6)
	}
	if !a.Less(3, 7) {
		a.Swap(3, 7)
	}
	if !a.Less(8, 12) {
		a.Swap(8, 12)
	}
	if !a.Less(9, 13) {
		a.Swap(9, 13)
	}
	if !a.Less(10, 14) {
		a.Swap(10, 14)
	}
	if !a.Less(11, 15) {
		a.Swap(11, 15)
	}
	if !a.Less(0, 2) {
		a.Swap(0, 2)
	}
	if !a.Less(1, 3) {
		a.Swap(1, 3)
	}
	if !a.Less(4, 6) {
		a.Swap(4, 6)
	}
	if !a.Less(5, 7) {
		a.Swap(5, 7)
	}
	if !a.Less(8, 10) {
		a.Swap(8, 10)
	}
	if !a.Less(9, 11) {
		a.Swap(9, 11)
	}
	if !a.Less(12, 14) {
		a.Swap(12, 14)
	}
	if !a.Less(13, 15) {
		a.Swap(13, 15)
	}
	if !a.Less(0, 1) {
		a.Swap(0, 1)
	}
	if !a.Less(2, 3) {
		a.Swap(2, 3)
	}
	if !a.Less(4, 5) {
		a.Swap(4, 5)
	}
	if !a.Less(6, 7) {
		a.Swap(6, 7)
	}
	if !a.Less(8, 9) {
		a.Swap(8, 9)
	}
	if !a.Less(10, 11) {
		a.Swap(10, 11)
	}
	if !a.Less(12, 13) {
		a.Swap(12, 13)
	}
	if !a.Less(14, 15) {
		a.Swap(14, 15)
	}
}
